### ISSUE TITLE
Whats the licence of the project?

### ISSUE THREAD

**Issue by agusnavce** [AlexEBall/Craft_and_Folk_Art_Museum_Mobile_App#2]
Hi, i want to use this as boilerplate for a university project, what is the licence?

**Comment by AlexEBall** [comment]
Hi @agusnavce, just added an MIT license. Feel free to use it as boilerplate for your project. Let me know how it goes of if you run into some issues

**Comment by agusnavce** [comment]
@AlexEBall Thanks for that. For now all running lean.
